ARG HIVE_VERSION=${HIVE_VERSION:-4.0.0}
FROM apache/hive:$HIVE_VERSION

SHELL ["/bin/bash", "-c"]

LABEL maintainer="Ranga Reddy <rangareddy.avula@gmail.com>"
LABEL description="Datalake Hive image"

USER root

RUN apt-get update && \
	apt-get install curl -y telnet vim jq net-tools && \
	mkdir -p /home/hive/.beeline && \
	chown hive /home/hive/.beeline

RUN ln -sf $HADOOP_HOME/share/hadoop/common/lib/guava-27.0-jre.jar $HIVE_HOME/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/aws-java-sdk-bundle-*.jar $HIVE_HOME/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/hadoop-aws*.jar $HIVE_HOME/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/aws-java-sdk-bundle-*.jar $HADOOP_HOME/share/hadoop/common/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/hadoop-aws-$HADOOP_VERSION.jar $HADOOP_HOME/share/hadoop/common/lib/ \
	&& rm /opt/hive/lib/log4j-slf4j-impl-*.jar

COPY conf/hive/* $HIVE_HOME/conf/
COPY db_connector_jars/* $HIVE_HOME/lib/

ARG HUDI_VERSION=${HUDI_VERSION:-1.0.2}
RUN curl -s https://repo1.maven.org/maven2/org/apache/hudi/hudi-hadoop-mr-bundle/${HUDI_VERSION}/hudi-hadoop-mr-bundle-${HUDI_VERSION}.jar \
	-o $HIVE_HOME/lib/hudi-hadoop-mr-bundle-${HUDI_VERSION}.jar

USER hive
