ARG TRINO_VERSION=${TRINO_VERSION:-460}
FROM trinodb/trino:${TRINO_VERSION}

SHELL ["/bin/bash", "-c"]

LABEL maintainer="Ranga Reddy <rangareddy.avula@gmail.com>"
LABEL description="Datalake Trino image"

USER root

COPY conf/trino/catalog /etc/trino/catalog
RUN chmod 755 /etc/trino/catalog

USER trino