ARG HIVE_VERSION=${HIVE_VERSION:-4.0.0}
FROM apache/hive:$HIVE_VERSION

LABEL maintainer="Ranga Reddy"
USER root

RUN apt-get update && \
	apt-get install curl -y telnet vim jq && \
	mkdir -p /home/hive/.beeline && \
	chown hive /home/hive/.beeline

RUN echo "Copying the requried jars." \
	&& ln -sf $HADOOP_HOME/share/hadoop/common/lib/guava-27.0-jre.jar $HIVE_HOME/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/aws-java-sdk-bundle-*.jar $HIVE_HOME/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/hadoop-aws*.jar $HIVE_HOME/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/aws-java-sdk-bundle-*.jar $HADOOP_HOME/share/hadoop/common/lib/ \
	&& ln -sf $HADOOP_HOME/share/hadoop/tools/lib/hadoop-aws-$HADOOP_VERSION.jar $HADOOP_HOME/share/hadoop/common/lib/ \
	&& rm /opt/hive/lib/log4j-slf4j-impl-*.jar

COPY db_connector_jars/* $HIVE_HOME/lib/
COPY conf/hive/hive-site.xml $HIVE_HOME/conf/
COPY conf/hive/beeline-site.xml $HIVE_HOME/conf/

USER hive